on: push
name: Build on Push
jobs:
  testGoPackage:
    name: Test Go Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12' # The Go version to download (if necessary) and use.
    - run: go test github.com/KalleDK/go-csv/csv
